{% set name = "psutil" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7be9c3eba38beccb6495ea33afd982a44074b78f28c434a1f51cc07fd315c456

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=43
    - wheel
  run:
    - python

test:
  requires:
    - pip

  imports:
    - psutil
    - psutil.tests

  commands:
    - pip check

about:
  home: https://github.com/giampaolo/psutil
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A cross-platform process and system utilities module for Python
  description: |
    psutil (process and system utilities) is a cross-platform library for
    retrieving information on running processes and system utilization (CPU,
    memory, disks, network) in Python. It is useful mainly for system
    monitoring, profiling and limiting process resources and management of
    running processes.
  doc_url: https://psutil.readthedocs.io
  dev_url: https://github.com/giampaolo/psutil

extra:
  recipe-maintainers:
    - gqmelo
    - jakirkham
    - jjhelmus
    - pelson
    - nehaljwani
