{% set name = "psutil" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7be9c3eba38beccb6495ea33afd982a44074b78f28c434a1f51cc07fd315c456

build:
  number: 0
  skip: true  # [py<36]
  script:
    - export CFLAGS="${CFLAGS} -DkIOMainPortDefault=kIOMasterPortDefault"  # [osx]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=43
    - wheel
  run:
    - python

# FileNotFoundError: [Errno 2] No such file or directory:
# '$PREFIX/lib/python3.12/site-packages/scripts/*'
{% set SKIP_TEST_FILES = [
    "psutil/tests/test_scripts.py"
] %}

{% set SKIP_TEST_OSX = [
    "test_disks",
    "test_vmem_active",
    "test_vmem_free",
    "test_vmem_inactive",
    "test_vmem_wired",
    "test_disk_usage",
    "test_all"
] %}

{% set SKIP_TEST_LINUX = [
    "test_against_findmnt",
    "test_comparisons",
    "test_disk_partitions_mocke",
    "test_cmdline",
    "test_name",
    "test_users",
    "test_pmap",
    "test_python2",
    "test_proc_name"
] %}

{% set SKIP_TEST_WIN = [
    "test_users",
    "test_pmap",
    "test_winservices",
    "test_long_cmdline"
] %}

{% set SKIP_TEST_LIST = [] %}
{% set SKIP_TEST_LIST = SKIP_TEST_LIST + SKIP_TEST_OSX %}  # [osx]
{% set SKIP_TEST_LIST = SKIP_TEST_LIST + SKIP_TEST_LINUX %}  # [linux]
{% set SKIP_TEST_LIST = SKIP_TEST_LIST + SKIP_TEST_WIN %}  # [win]

test:
  source_files:
    - psutil/tests
  requires:
    - pip
    - pytest
  imports:
    - psutil
    - psutil.tests
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pip install pywin32 wmi # [win]
    - pytest psutil/tests {% for file in SKIP_TEST_FILES %} --ignore={{ file }}{% endfor %} -v -k "not ({{ SKIP_TEST_LIST | join(' or ') }})"

about:
  home: https://github.com/giampaolo/psutil
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A cross-platform process and system utilities module for Python
  description: |
    psutil (process and system utilities) is a cross-platform library for
    retrieving information on running processes and system utilization (CPU,
    memory, disks, network) in Python. It is useful mainly for system
    monitoring, profiling and limiting process resources and management of
    running processes.
  doc_url: https://psutil.readthedocs.io
  dev_url: https://github.com/giampaolo/psutil

extra:
  recipe-maintainers:
    - gqmelo
    - jakirkham
    - jjhelmus
    - pelson
    - nehaljwani
