{% set name = "psutil" %}
{% set version = "5.9.0" %}
{% set sha256 = "869842dbd66bb80c3217158e629d6fceaecc3a3166d3d1faee515b05dd26ca25" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install --ignore-installed --no-deps .
  skip: true  # [py<26 or py==30 or py==31 or py==32 or py==33]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - ipaddress    # [py<30]
    - mock         # [py<30]
    - unittest2    # [py<30]
    - enum34       # [py<35]
    - pip

  imports:
    - psutil
    - psutil._psutil_posix    # [unix]
    - psutil._psutil_linux    # [linux]
    - psutil._psutil_osx      # [osx]
    - psutil._psutil_windows  # [win]
    - psutil.tests

  commands:
    - pip check

about:
  home: https://github.com/giampaolo/psutil
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A cross-platform process and system utilities module for Python
  description: |
    psutil (process and system utilities) is a cross-platform library for
    retrieving information on running processes and system utilization (CPU,
    memory, disks, network) in Python. It is useful mainly for system
    monitoring, profiling and limiting process resources and management of
    running processes.
  doc_url: https://psutil.readthedocs.io/en/latest/
  doc_source_url: https://github.com/giampaolo/psutil/blob/master/docs/index.rst
  dev_url: https://github.com/giampaolo/psutil

extra:
  recipe-maintainers:
    - gqmelo
    - jakirkham
    - jjhelmus
    - pelson
    - nehaljwani
