{% set name = "psutil" %}
{% set version = "5.2.0" %}
{% set sha256 = "2fc91d068faa5613c093335f0e758673ef8c722ad4bfa4aded64c13ae69089eb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }} 

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - ipaddress    # [py<33]
    - mock         # [py<33]
    - unittest2    # [py<27]

  imports:
    - psutil
    - psutil.tests

about:
  home: https://github.com/giampaolo/psutil
  license: BSD 3-Clause
  summary: A cross-platform process and system utilities module for Python

extra:
  recipe-maintainers:
    - gqmelo
    - jakirkham
    - pelson
