travis:
  secure:
    BINSTAR_TOKEN: hdKTcUhm4meLk1XT9250fxIXvYoFWBMGgfGJlpdUrsd8oOmJ20OL6VQI/nf5ukqfYCsO/kCiTWak4XbzI7r7EX+Z/QJKERgKUw/IZJ4aAPvJBZrK3JJtdO3Y1cxTDdMPhsWy4Op5w7bHI/N+R9ENO3a0wE7neBH8rbkXub5wPxrRWZ8ofCX+pYQT9xR8oDAZMg9Ul5w7RmFJTMWRcx0cN6yMseF7aO0fNH9A1xUBt1GgNA44F2rMDEKV7f+A8IvUJZzw9SduoZJbrXmCEV93N/HOMiIcYLR2Pjyye1O+/hREWLiO+Nyc+4hGOIefNu7Urh+AWRzqFLt96fv020zyUHBl1njdzLO1cu4NMtUPWN+5sB/mXr2+vDvBjN2kWoMpZq4QOXNRDIcRtjUsvGRnrQQfnun3eggq9kV/2FDSkhnlz7g3Ff5QbeevtJcnoSnb/0erlFOTBhSrflat6IUEkiTplu5OlfteMLKGqJSY44JJ0p9Ie44QwFbIwJTOp6lciYZ9gFBpqP/Hr3rb6kv4NEhulGHkNEL4NG6sNyji1iV0gWcl+uTjnfrN07I8PXH+DZo4EtFPDRUoXB0B6mRVOSXys3KeDlfpmst6+Xqpgfq2VWxkWqKPBUjUIp5fzUqM+AyzkAY60L49Lo2tR5QD8Jh9xoZhTluUwRxAeje0KkI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
